SELECT DISTINCT
A.*,
CASE WHEN B.CHF_ID IS NOT NULL THEN B.CHF_ID ELSE 0 END AS CHF_ID,
CASE WHEN B.COPD_ID IS NOT NULL THEN B.COPD_ID ELSE 0 END AS COPD_ID,
CASE WHEN B.CAD_ID IS NOT NULL THEN B.CAD_ID ELSE 0 END AS CAD_ID,
CASE WHEN B.DIA_ID IS NOT NULL THEN B.DIA_ID ELSE 0 END AS DIA_ID,
CASE WHEN B.ASTHM_ID IS NOT NULL THEN B.ASTHM_ID ELSE 0 END AS ASTHM_ID,
CASE WHEN B.ALT_PRSN_ID IS NOT NULL THEN 1 ELSE 0 END AS DM_IDENTIFIED,
 CASE WHEN  B.NUM_CHRONIC_COND > 0 THEN B.NUM_CHRONIC_COND ELSE 0  END AS NUM_CHRONIC_COND,
 CASE WHEN  B.PRIMARY_CONDITION IS NOT NULL THEN B.PRIMARY_CONDITION ELSE 'NotAny'  END AS PRIMARY_CONDITION
FROM ELI_MEMBER2 AS A 
LEFT JOIN  ID_LAST  AS B
ON  A.ALT_PRSN_ID=B.ALT_PRSN_ID
;
